version: "3"

services:
  # Сервер с хранилищем файлов.
  s3:
    image: minio/minio:latest
    container_name: miniodocker
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - "../media:/data"
    environment:
      - MINIO_ACCESS_KEY=9QO0C55OGEG79FWQGCGW
      - MINIO_SECRET_KEY=S00ICE545g3M8b9RqM2xCNFuGlU6wKy2rkVJAz5y
    restart: on-failure

  # База
  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo_docker
    restart: always
    ports:
      - "27017:27017"

  # Postfix для отправки почты
  postfix:
    image: catatnight/postfix
    container_name: postfix_docker
    environment:
      - maildomain=localhost
      - smtp_user=user:password

  # Наше приложение для отправки почты
  postfix_backend:
    container_name: postfix_backend__docker
    build:
      dockerfile: Dockerfile
      context: ./postfix_application
    depends_on:
      - postfix
    # links можно не писать
    links:
      - postfix
    environment:
      - SMTP_HOST=postfix
      - SMTP_PORT=25
      - SMTP_USER=user
      - SMTP_PASSWORD=password
      - EMAIL_BACKEND_PORT=5000
    restart: "no"

  zookeeper:
    image: zookeeper:3.4.12
    ports:
      - "2181:2181"

  kafka:
    image: nxexox/kafka-lesson-example:latest
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - "9092:9092"

  # Наше приложение.
  backend:
    container_name: backend_docker
    build:
      dockerfile: Dockerfile
      context: ./application
    depends_on:
      - s3
      - mongo
      - postfix_backend
      - kafka
    # links можно не писать
    links:
      - s3
      - mongo
      - postfix_backend
      - kafka
    environment:
      - MINIO_HOST=s3
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=9QO0C55OGEG79FWQGCGW
      - MINIO_SECRET_KEY=S00ICE545g3M8b9RqM2xCNFuGlU6wKy2rkVJAz5y
      - MINIO_BUCKET_NAME=bucket
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo
      - EMAIL_SERVICE_HOST=postfix_backend
      - EMAIL_SERVICE_PORT=5000
      - BACKEND_PORT=5000
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPICS=worker1,worker2
      - ENVIRONMENT=application
    restart: "no"
  # Воркер 1
  worker1:
    container_name: worker1_docker
    command: python worker.py
    build:
      dockerfile: Dockerfile
      context: ./application
    depends_on:
      - s3
      - mongo
      - postfix_backend
      - kafka
    links:
      - s3
      - mongo
      - postfix_backend
      - kafka
    environment:
      - MINIO_HOST=s3
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=9QO0C55OGEG79FWQGCGW
      - MINIO_SECRET_KEY=S00ICE545g3M8b9RqM2xCNFuGlU6wKy2rkVJAz5y
      - MINIO_BUCKET_NAME=bucket
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo
      - EMAIL_SERVICE_HOST=postfix_backend
      - EMAIL_SERVICE_PORT=5000
      - BACKEND_PORT=5000
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=worker1
      - ENVIRONMENT=worker
    restart: "no"
  # Воркер 2
  worker2:
    container_name: worker2_docker
    command: python worker.py
    build:
      dockerfile: Dockerfile
      context: ./application
    depends_on:
      - s3
      - mongo
      - postfix_backend
      - kafka
    links:
      - s3
      - mongo
      - postfix_backend
      - kafka
    environment:
      - MINIO_HOST=s3
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=9QO0C55OGEG79FWQGCGW
      - MINIO_SECRET_KEY=S00ICE545g3M8b9RqM2xCNFuGlU6wKy2rkVJAz5y
      - MINIO_BUCKET_NAME=bucket
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo
      - EMAIL_SERVICE_HOST=postfix_backend
      - EMAIL_SERVICE_PORT=5000
      - BACKEND_PORT=5000
      - KAFKA_HOST=kafka
      - KAFKA_PORT=9092
      - KAFKA_TOPIC=worker2
      - ENVIRONMENT=worker
    restart: "no"

  # Веб сервер как морда
  nginx:
    container_name: nginx_docker
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
    depends_on:
      - backend
    ports:
      - "8000:80"
    restart: "no"
