apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    app: application-task-1
spec:
  containers:
    - name: application-task-1
      image: registry.skbkontur.ru/mc-k8s/task-1:application
      env:
        - name: USER_NAME
          value: "Введите тут свое имя"
