kind: Service
apiVersion: v1
metadata:
  name: application-front
spec:
  selector:
    app: application-front
  type: NodePort  # Для доступа без ingress
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
    # nodePort: 30333  # Порт что торчит наружу, если не указывать назначается автоматически
