version: "3"

services:
  # Сервер с хранилищем файлов.
  s3:
    image: minio/minio:latest
    container_name: miniodocker1
    command: server /data
    ports:
      - "9000:9000"
    volumes:
      - ../media:/data
    environment:
      - MINIO_ACCESS_KEY=9QO0C55OGEG79FWQGCGW
      - MINIO_SECRET_KEY=S00ICE545g3M8b9RqM2xCNFuGlU6wKy2rkVJAz5y

  # База
  mongo:
    image: bitnami/mongodb:latest
    container_name: mongo_docker_1
    restart: always

  # Наше приложение.
  backend:
    container_name: backend_docker_1
    build:
      dockerfile: Dockerfile
      context: ./application
    depends_on:
      - s3
      - mongo
    environment:
      - MINIO_HOST=s3
      - MINIO_PORT=9000
      - MINIO_ACCESS_KEY=9QO0C55OGEG79FWQGCGW
      - MINIO_SECRET_KEY=S00ICE545g3M8b9RqM2xCNFuGlU6wKy2rkVJAz5y
      - MINIO_BUCKET_NAME=bucket
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DATABASE=mongo

  # Веб сервер как морда
  nginx:
    container_name: nginx_docker_1
    build:
      context: ./nginx
      dockerfile: Dockerfile
    environment:
      - BACKEND_HOST=backend
      - BACKEND_PORT=5000
    depends_on:
      - backend
    ports:
      - "8000:80"
